### ISSUE TITLE
Doors look weird when open

### ISSUE THREAD

**Issue by Versus506** [chatrat12/Terraria3D#24] opened 2019-02-01 17:38 UTC
![zrzut ekranu 153](https://user-images.githubusercontent.com/39453579/52139429-6da0ba80-2650-11e9-999f-b5af94034137.png)

**Comment by prgmatic** [comment] 2019-02-03 08:55
Thanks for the report. Duplicate of #14

**Closed as completed by prgmatic** 2019-02-03 08:55 UTC
Labels: duplicate
